apiVersion: apps/v1
kind: Deployment
metadata:
  name: lock-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lock-mgr
  template:
    metadata:
      labels:
        app: lock-mgr
    spec:
      containers:
      - name: lock-mgr
        image: jcostaasc/qumulo-lock-mgr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        volumeMounts:
        - name: config-volume
          mountPath: /usr/app
      volumes:
      - name: config-volume
        configMap:
          name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: lock-mgr-service
spec:
  selector:
    app: lock-mgr
  ports:
    - protocol: TCP
      port: 443
      targetPort: 4000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  async_main.conf: |
    [CLUSTER]
    CLUSTER_ADDRESS = your.cluster.company.com
    # Set this to False to ignore self-signed TLS errors
    USE_SSL = False

    [WEBUI_ADMIN]
    USERNAME = admin_user
    PASSWORD = Admin_Password123
    TOKEN = access-v1:bar..baz..foo

    [WEBUI_READONLY]
    USERNAME = ro_user
    PASSWORD = RO_Password123
    TOKEN = access-v1:foo..bar..baz